# Generated by Django 3.2.9 on 2021-12-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentariu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentariu', models.TextField(max_length=200, verbose_name='Comentariu')),
            ],
        ),
    ]
